apiVersion: v1
kind: Service
metadata:
  name: juice-shop
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: juice-shop
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
